stages:
  - lint
  - production

lint:
  stage: lint
  image: node:20.10.0
  script:
    - apt-get update && apt-get install -y git wget curl build-essential python3 
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - git submodule update --init
    - pnpm install --frozen-lockfile
    - pnpm --filter cherrypick-js run build
    - pnpm --filter misskey-reversi run build
    - pnpm --filter backend run typecheck
    - pnpm --filter frontend run eslint

production:
  stage: production
  image: node:20.10.0
  script:
    - apt-get update && apt-get install -y git wget curl build-essential python3 
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - git submodule update --init
    - pnpm install --frozen-lockfile
    - git diff --exit-code pnpm-lock.yaml
    - cp .github/cherrypick/test.yml .config/default.yml
    - pnpm run build