name: Test (production install and build)

on:
  push:
    branches:
      - master
      - release
  pull_request:

env:
  NODE_ENV: production

jobs:
  production:
    runs-on: docker

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - name: Install pnpm
      uses: https://github.com/pnpm/action-setup@v3
      with:
        version: 8
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: https://code.forgejo.org/actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/cherrypick/test.yml .config/default.yml
    - name: Build
      run: pnpm build
