/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const DI = {
	config: Symbol('config'),
	db: Symbol('db'),
	meilisearch: Symbol('meilisearch'),
	cloudLogging: Symbol('cloudLogging'),
	redis: Symbol('redis'),
	redisForPub: Symbol('redisForPub'),
	redisForSub: Symbol('redisForSub'),
	redisForTimelines: Symbol('redisForTimelines'),
	redisForJobQueue: Symbol('redisForJobQueue'),

	//#region Repositories
	usersRepository: Symbol('usersRepository'),
	notesRepository: Symbol('notesRepository'),
	abuseReportResolversRepository: Symbol('abuseReportResolversRepository'),
	announcementsRepository: Symbol('announcementsRepository'),
	announcementReadsRepository: Symbol('announcementReadsRepository'),
	appsRepository: Symbol('appsRepository'),
	avatarDecorationsRepository: Symbol('avatarDecorationsRepository'),
	noteFavoritesRepository: Symbol('noteFavoritesRepository'),
	noteThreadMutingsRepository: Symbol('noteThreadMutingsRepository'),
	noteReactionsRepository: Symbol('noteReactionsRepository'),
	noteUnreadsRepository: Symbol('noteUnreadsRepository'),
	pollsRepository: Symbol('pollsRepository'),
	pollVotesRepository: Symbol('pollVotesRepository'),
	userProfilesRepository: Symbol('userProfilesRepository'),
	userKeypairsRepository: Symbol('userKeypairsRepository'),
	userPendingsRepository: Symbol('userPendingsRepository'),
	userSecurityKeysRepository: Symbol('userSecurityKeysRepository'),
	userPublickeysRepository: Symbol('userPublickeysRepository'),
	userListsRepository: Symbol('userListsRepository'),
	userListFavoritesRepository: Symbol('userListFavoritesRepository'),
	userListMembershipsRepository: Symbol('userListMembershipsRepository'),
	userGroupsRepository: Symbol('userGroupsRepository'),
	userGroupJoiningsRepository: Symbol('userGroupJoiningsRepository'),
	userGroupInvitationsRepository: Symbol('userGroupInvitationsRepository'),
	userNotePiningsRepository: Symbol('userNotePiningsRepository'),
	userIpsRepository: Symbol('userIpsRepository'),
	usedUsernamesRepository: Symbol('usedUsernamesRepository'),
	followingsRepository: Symbol('followingsRepository'),
	followRequestsRepository: Symbol('followRequestsRepository'),
	instancesRepository: Symbol('instancesRepository'),
	emojisRepository: Symbol('emojisRepository'),
	eventsRepository: Symbol('eventsRepository'),
	driveFilesRepository: Symbol('driveFilesRepository'),
	driveFoldersRepository: Symbol('driveFoldersRepository'),
	metasRepository: Symbol('metasRepository'),
	mutingsRepository: Symbol('mutingsRepository'),
	renoteMutingsRepository: Symbol('renoteMutingsRepository'),
	blockingsRepository: Symbol('blockingsRepository'),
	swSubscriptionsRepository: Symbol('swSubscriptionsRepository'),
	hashtagsRepository: Symbol('hashtagsRepository'),
	abuseUserReportsRepository: Symbol('abuseUserReportsRepository'),
	registrationTicketsRepository: Symbol('registrationTicketsRepository'),
	authSessionsRepository: Symbol('authSessionsRepository'),
	accessTokensRepository: Symbol('accessTokensRepository'),
	signinsRepository: Symbol('signinsRepository'),
	messagingMessagesRepository: Symbol('messagingMessagesRepository'),
	pagesRepository: Symbol('pagesRepository'),
	pageLikesRepository: Sy	bol('pageLikesRepository'),
	galleryPostsRep	sitory: Symbol('galleryPostsRepository'),
	galleryLi	esRepository: Symbol('galleryLikesRepository'),
	moderatio	LogsRepository: Symbol('moderationLogsRepository'),
	clips	epository: Symbol('clipsRepository'),
	clipNotesRepository: Sy	bol('clipNotesRepository'),
	clipFavoritesRe	ository: Symbol('clipFavoritesRepository'),
	antenna	Repository: Symbol('antennasRepository'),
	promoNotesReposit	ry: Symbol('promoNotesRepository'),
	promoReadsRep	sitory: Symbol('promoReadsRepository'),
	relaysReposit	ry: Symbol('relaysRepository'),
	channelsRepository: S	mbol('channelsRepository'),
	channelFollowings	epository: Symbol('channelFollowingsRepository'),
	channelFavoritesRepository: Symbol('channelFavoritesRepository'),
	r	gistryItemsRepository: Symbol('registryItemsRepository'),
	webhook	Repository: Symbol('webhooksRepository'),
	adsRepository: Sy	bol('adsRepository'),
	passwordResetRequestsReposi	ory: Symbol('passwordResetRequestsReposi	ory'),
	retentionAggregationsRepository: Symbol('retentionAggregationsReposi	ory'),
	rolesRepository: Symbol('rolesRepository'),
	roleAssignmentsReposito	y: Symbol('roleAssignmentsRepository'),
	fla	hsRepository: Symbol('flashsRepository'),
	flashLikesRepository:	Symbol('flashLikesRepository'),
	userMemosRepo	itory: Symbol('userMemosRepository'),
	bubbleGameRecor	sRepository: Symbol('bubbleGameRecordsRepository'),
	reversiGamesRepository: Symbol('reversiGamesRepository'),
	//#endreg	on
};
